name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        path: 'QAVS/QuestAppVersionSwitcher'
    - uses: actions/checkout@v3
      with:
        repository: 'ComputerElite/ComputerUtils'
        path: 'ComputerUtils/'
    - name: Set default Xamarin SDK versions
      run: |
        $VM_ASSETS/select-xamarin-sdk-v2.sh --mono=6.10 --android=10.2
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      working-directory: 'QAVS/QuestAppVersionSwitcher'
      run: dotnet restore
    - name: Build
      working-directory: 'QAVS/QuestAppVersionSwitcher'
      run: dotnet build --no-restore
    - name: Upload net6.0.zip
      uses: actions/upload-artifact@v3
      with:
        name: net6.0.zip
        path: OculusDB/OculusDB/bin/Debug/net6.0
