name: .NET

# Run on every push on main branch
on:
  workflow_dispatch:
  push:
    branches: [ main,adb ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
      with:
        path: 'QAVS'
        submodules: recursive


    - name: Cache NuGet packages
      uses: actions/cache@v3
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('QAVS/**/*.csproj') }}-${{ hashFiles('ComputerUtils/**/*.csproj') }}
        restore-keys: |
          ${{ runner.os }}-nuget-

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - uses: actions/setup-java@v1
      with:
        java-version: '11'


    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1

    - name: Restore dependencies
      working-directory: 'QAVS'
      run: nuget restore

    - name: Build
      working-directory: 'QAVS\QuestAppVersionSwitcher'
      run: msbuild QuestAppVersionSwitcher.csproj /t:PackageForAndroid /t:SignAndroidPackage  /p:Configuration=Release

    - name: Generate .jks signing key on the fly
      shell: pwsh
      run: |
        & keytool -genkeypair `
          -alias "${{ secrets.ALIAS }}" `
          -keyalg RSA `
          -keysize 2048 `
          -validity 365 `
          -keystore signing_key.jks `
          -dname "CN=Your Name, OU=Org Unit, O=Org, L=City, S=State, C=US" `
          -storepass "${{ secrets.KEY_STORE_PASSWORD }}" `
          -keypass "${{ secrets.KEY_PASSWORD }}"
        
        # Convert the .jks file to base64 and save it to an environment variable
        $base64Key = [Convert]::ToBase64String([System.IO.File]::ReadAllBytes("signing_key.jks"))
        echo "SIGNING_KEY=$base64Key" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8

    
    - uses: r0adkll/sign-android-release@v1.0.4
      name: Sign app APK
      id: sign_app
      with:
        releaseDirectory: QAVS/QuestAppVersionSwitcher/bin/Release
        signingKeyBase64: ${{ env.SIGNING_KEY }}
        alias: ${{ secrets.ALIAS }}
        keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
      env:
        # override default build-tools version (29.0.3) -- optional
        BUILD_TOOLS_VERSION: "33.0.2"

    # Example use of `signedReleaseFile` output -- not needed
    - uses: actions/upload-artifact@v4
      with:
        name: Signed app bundle
        path: ${{steps.sign_app.outputs.signedReleaseFile}}
